version: '2.2'
services:
  app:
    image:
      web-post
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=development

